import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { GRAPH_POINTS, graphPaths, graphPoint, graphSvg } from './graph-mark.js'

const vertices = (path) => [...path.matchAll(/[ML]([\d.-]+),([\d.-]+)/g)].map(([, x, y]) => [+x, +y])
const radius = ([x, y]) => Math.hypot(x - 24, y - 24)

describe('size-specific graph marks', () => {
  it.each([[20, 44, .7], [32, 66, .46], [56, 110, .23], [160, 220, .08]])('keeps the approved connection count and width at %ipx', (size, count, width) => {
    const graph = graphPaths(size)
    expect(graph.edges.match(/M/g)).toHaveLength(count)
    expect(graph.width).toBe(width)
    expect(graph.points.map(point => point.map(n => +n.toFixed(2)))).toEqual(GRAPH_POINTS)
    expect(graphSvg(size).includes('<circle')).toBe(size >= 96)
  })

  it('contracts the opening while expanding the outer teeth at peak pulse', () => {
    const rest = vertices(graphPaths(20).edges).map(radius)
    const peak = vertices(graphPaths(20, { scale: 1.032, ampMul: 1.6, widthMul: 1.18 }).edges).map(radius)
    expect(Math.min(...peak)).toBeLessThan(Math.min(...rest) - 3)
    const outerRest = Math.max(...GRAPH_POINTS.map(radius))
    const outerPeak = Math.max(...GRAPH_POINTS.map(p => radius(graphPoint(p, { scale: 1.032, ampMul: 1.6 }))))
    expect(outerPeak).toBeGreaterThan(outerRest)
  })

  it('ships the static authentication variant generated by the shared geometry', () => {
    const svg = readFileSync('src-tauri/icons/muniment-graph-auth.svg', 'utf8').replace(/<style>.*?<\/style>/s, '').trim()
    expect(svg).toBe(graphSvg(56))
    expect(svg).not.toMatch(/<animate|<script/)
  })
})
