[package]
name = "muniment-cli"
version = "0.0.1"
edition = "2021"

[dependencies]
muniment-attach = { git = "https://github.com/munimentai/muniment-core", tag = "v1.12.6", default-features = false, features = ["client"] }
muniment-code-diff = { git = "https://github.com/munimentai/muniment-core", tag = "v1.12.6" }
serde_json = "1"
