[package]
name = "muniment-runtime"
version = "0.0.1"
edition = "2021"

[dependencies]
serde_json = "1"
muniment-attach = { path = "../attach", features = ["client"] }
muniment-core = { path = "../core", features = ["keyring", "tls"] }

[dev-dependencies]
keyring = { version = "3", default-features = false }
